### GET ALL BOOKS
GET /api/books HTTP/1.1
Content-Type: application/json
Host: localhost:3000

### 1 - REGISTER BOOKS
POST /api/books HTTP/1.1
Content-Type: application/json
Host: localhost:3000

{
    "title": "DDD",
    "author": "Jhon Doe",
    "category": "technology"
}

### SEARCH BOOKS
GET /api/books/find/DDD HTTP/1.1
Content-Type: application/json
Host: localhost:3000


### 2 - REGISTER USER
POST /api/users HTTP/1.1
Content-Type: application/json
Host: localhost:3000

{
    "user_id": "1",
    "name": "Jhon Doe",
    "user_type": "student"
}

### FIND USER
GET /api/users/find/1 HTTP/1.1
Content-Type: application/json
Host: localhost:3000

### 3 - BORROW BOOKS
POST /api/borrow/ HTTP/1.1
Content-Type: application/json
Host: localhost:3000

{
    "user_id": "1",
    "title": "DDD"
}

### 4 - RETURN BOOKS
POST /api/return/ HTTP/1.1
Content-Type: application/json
Host: localhost:3000

{
    "user_id": "1",
    "title": "DDD"
}